/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AfricaRouteImport } from './routes/africa'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LiaRouteImport } from './routes/lia'
import { Route as MethodRouteImport } from './routes/method'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PricingPhilosophyRouteImport } from './routes/pricing-philosophy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AfricaRoute = AfricaRouteImport.update({
  id: '/africa',
  path: '/africa',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LiaRoute = LiaRouteImport.update({
  id: '/lia',
  path: '/lia',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingPhilosophyRoute = PricingPhilosophyRouteImport.update({
  id: '/pricing-philosophy',
  path: '/pricing-philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/africa': typeof AfricaRoute
  '/apps': typeof AppsRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/lia': typeof LiaRoute
  '/method': typeof MethodRoute
  '/pricing': typeof PricingRoute
  '/pricing-philosophy': typeof PricingPhilosophyRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRouteWithChildren
  '/work/$slug': typeof WorkSlugRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/africa': typeof AfricaRoute
  '/apps': typeof AppsRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/lia': typeof LiaRoute
  '/method': typeof MethodRoute
  '/pricing': typeof PricingRoute
  '/pricing-philosophy': typeof PricingPhilosophyRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/terms': typeof TermsRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/africa': typeof AfricaRoute
  '/apps': typeof AppsRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/lia': typeof LiaRoute
  '/method': typeof MethodRoute
  '/pricing': typeof PricingRoute
  '/pricing-philosophy': typeof PricingPhilosophyRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRouteWithChildren
  '/work/$slug': typeof WorkSlugRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/africa'
    | '/apps'
    | '/company'
    | '/contact'
    | '/lia'
    | '/method'
    | '/pricing'
    | '/pricing-philosophy'
    | '/privacy'
    | '/research'
    | '/terms'
    | '/work'
    | '/work/$slug'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/africa'
    | '/apps'
    | '/company'
    | '/contact'
    | '/lia'
    | '/method'
    | '/pricing'
    | '/pricing-philosophy'
    | '/privacy'
    | '/research'
    | '/terms'
    | '/work/$slug'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/africa'
    | '/apps'
    | '/company'
    | '/contact'
    | '/lia'
    | '/method'
    | '/pricing'
    | '/pricing-philosophy'
    | '/privacy'
    | '/research'
    | '/terms'
    | '/work'
    | '/work/$slug'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AfricaRoute: typeof AfricaRoute
  AppsRoute: typeof AppsRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  LiaRoute: typeof LiaRoute
  MethodRoute: typeof MethodRoute
  PricingRoute: typeof PricingRoute
  PricingPhilosophyRoute: typeof PricingPhilosophyRoute
  PrivacyRoute: typeof PrivacyRoute
  ResearchRoute: typeof ResearchRoute
  TermsRoute: typeof TermsRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/africa': {
      id: '/africa'
      path: '/africa'
      fullPath: '/africa'
      preLoaderRoute: typeof AfricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lia': {
      id: '/lia'
      path: '/lia'
      fullPath: '/lia'
      preLoaderRoute: typeof LiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-philosophy': {
      id: '/pricing-philosophy'
      path: '/pricing-philosophy'
      fullPath: '/pricing-philosophy'
      preLoaderRoute: typeof PricingPhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface WorkRouteChildren {
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AfricaRoute: AfricaRoute,
  AppsRoute: AppsRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  LiaRoute: LiaRoute,
  MethodRoute: MethodRoute,
  PricingRoute: PricingRoute,
  PricingPhilosophyRoute: PricingPhilosophyRoute,
  PrivacyRoute: PrivacyRoute,
  ResearchRoute: ResearchRoute,
  TermsRoute: TermsRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
